### ISSUE TITLE
Crashes without opening a window

### ISSUE THREAD

**Issue by UniqueName12345** [quasar098/midi-playground#1]
Hello! I downloaded it and ran the command `python3 main.py ./samples/ba.mid -m ba.mid `(yes, in case you were wondering I was trying to see how it would do with bad apple), but instead of running it just gave me this error code:

`Traceback (most recent call last):
  File "C:\Users\smurf\Documents\GitHub\midi-playground\main.py", line 44, in <module>
    main()
  File "C:\Users\smurf\Documents\GitHub\midi-playground\main.py", line 40, in main
    do_bouncing(filtered_args)
  File "C:\Users\smurf\Documents\GitHub\midi-playground\bouncegen.py", line 459, in do_the_things
    _, notes = read_midi_file(midi_file_name)
  File "C:\Users\smurf\Documents\GitHub\midi-playground\shared.py", line 34, in read_midi_file
    for msg in mid:
  File "C:\Users\smurf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mido\midifiles\midifiles.py", line 384, in __iter__
    for msg in merge_tracks(self.tracks):
  File "C:\Users\smurf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mido\midifiles\tracks.py", line 110, in merge_tracks
    messages.extend(_to_abstime(track))
  File "C:\Users\smurf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mido\midifiles\tracks.py", line 68, in _to_abstime
    yield msg.copy(time=now)
  File "C:\Users\smurf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mido\midifiles\meta.py", line 507, in copy
    return self.__class__(**attrs)
TypeError: UnknownMetaMessage.__init__() got an unexpected keyword argument 'type'`

Anyway I can fix this?

**Comment by UniqueName12345** [comment]
> it seems to be an error with your mido package installation. can you try uninstalling and reinstalling the mido package? additionally, the -m flag takes in a full path, and i assume ba.mid is not in both the current directory and the samples directory (only the samples directory)?

both didn't work

**Comment by quasar098** [comment]
i think it is because you installed python in a strange way (not from python website), like from windows store or winget in powershell or something. perhaps try with python 3.9.1 from python website, as that is what is working for me. if it is truly not working, i will make a docker image container thing that you can just run it on maybe that will work

**Comment by quasar098** [comment]
are you there

**Comment by UniqueName12345** [comment]
> are you there

yes

**Comment by UniqueName12345** [comment]
> i think it is because you installed python in a strange way (not from python website), like from windows store or winget in powershell or something. perhaps try with python 3.9.1 from python website, as that is what is working for me. if it is truly not working, i will make a docker image container thing that you can just run it on maybe that will work

tried that, still didn't work
