### ISSUE TITLE
Startup

### ISSUE THREAD

**Issue by flipthebottleboy** [quasar098/midi-playground#104]
Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "utils.py", line 25, in <module>
pywintypes.error: (0, 'EnumDisplaySettings', 'No error message is available')
Idk What to Do tbh
![image_2024-05-08_212216766](https://github.com/quasar098/midi-playground/assets/114115902/0d21187b-0f23-460d-bcc1-9a674b137fd4)

**Comment by furry1465** [comment]
you had the same error as me

**Comment by flipthebottleboy** [comment]
> you had the same error as me

Did you fix it?

**Comment by furry1465** [comment]
> > you had the same error as me
> 
> Did you fix it?

no it didn't get replies
:(

**Comment by quasar098** [comment]
idk what is going on here
