### ISSUE TITLE
Game Crashes when selecting a song

### ISSUE THREAD

**Issue by FormunaGit** [quasar098/midi-playground#107]
For some reason, it only can play the Wii theme.
**The log:**
```
pygame-ce 2.4.1 (SDL 2.28.5, Python 3.10.12)
Traceback (most recent call last):
  File "/home/formuna/Downloads/midi-playground-master/main.py", line 228, in <module>
    main()
  File "/home/formuna/Downloads/midi-playground-master/main.py", line 178, in main
    song = song_selector.handle_event(event)
  File "/home/formuna/Downloads/midi-playground-master/songselector.py", line 179, in handle_event
    pygame.mixer.music.load(BytesIO(f.read()))
pygame.error: Couldn't open timidity.cfg
```
**Hardware and Software**
CPU: AMD Athlon Silver 3050U with Radeon Graphics
OS: Linux Mint 21.3 x86_64
RAM: 8gb
Version of MIDI Playground: 3.0.0 i think?
Verion of Python: Python 3.10.12
**Steps to recreate**
1. Download the source code.
2. Run `python3 -m pip install -r requirements.txt` inside the extracted `.zip` file.
3. Run `python3 main.py` and select Play
4. Choose any song (not Wii theme?)
- Crash

**Comment by FormunaGit** [comment]
New note: Same problem after reinstalling MIDI Playground, AND in a virtual enviroment!

**Comment by quasar098** [comment]
i think there was a previous issue where  a guy had the timidity.cfg issue on linux

https://github.com/quasar098/midi-playground/issues/86
also https://github.com/quasar098/midi-playground/issues/28

also a potential fix might be here
https://github.com/pygame/pygame/issues/343

**Comment by Coobik1234** [comment]
It's the same issue as mine

**Comment by quasar098** [comment]
did you manage to fix it because i have no clue what is going on

**Comment by Coobik1234** [comment]
Sadly i did not, but i convert all the midi to flac and that works.
