### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by DimaErmolaev07** [quasar098/midi-playground#108]
```
Traceback (most recent call last):
  File "main.py", line 228, in <module>
  File "main.py", line 44, in main
pygame.error: regular vsync for OpenGL not available
```
When I launch this app, there is a crash with this error, but sound is playing. How to fix that?

**Comment by quasar098** [comment]
idk

**Comment by admmm34** [comment]
me toooo pls solution

**Comment by admmm34** [comment]
> ```
> Traceback (most recent call last):
>   File "main.py", line 228, in <module>
>   File "main.py", line 44, in main
> pygame.error: regular vsync for OpenGL not available
> ```
> 
> When I launch this app, there is a crash with this error, but sound is playing. How to fix that?

did you find solution
