### ISSUE TITLE
Recursive bounce generation algorithm failed

### ISSUE THREAD

**Issue by M4yd3** [quasar098/midi-playground#14]
Just crashes whenever I try to play any song.
```D:\Soft\Python\python.exe D:/Documents/Projects/PyCharm/midi-playground/main.py
pygame 2.4.0 (SDL 2.26.4, Python 3.9.1)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "D:\Documents\Projects\PyCharm\midi-playground\main.py", line 135, in <module>
    main()
  File "D:\Documents\Projects\PyCharm\midi-playground\main.py", line 105, in main
    if game.start_song(screen):
  File "D:\Documents\Projects\PyCharm\midi-playground\game.py", line 60, in start_song
    self.safe_areas = self.world.gen_future_bounces(self.notes, update_loading_screen)
  File "D:\Documents\Projects\PyCharm\midi-playground\world.py", line 162, in gen_future_bounces
    assert self.future_bounces is not False, "Recursive bounce generation algorithm failed"
AssertionError: Recursive bounce generation algorithm failed

Process finished with exit code 1
```

**Comment by TheCodingCrafter** [comment]
decrease the square size to 20, in config.py, that worked for me

**Comment by M4yd3** [comment]
Didn't work, unfortunately. The square is definitely smaller as that can be seen in the main menu, but the issue is still there.

**Comment by quasar098** [comment]
it's an error with the square teleporting inside of the peg when it bounces. the way the algorithms works is that none of the square path should collide with the pegs but i think it is not working for some people because of square speed and framerate disparity. give me some time to get back to my computer and i will fix this up
