### ISSUE TITLE
song file doesnt work, can i get help as to why?

### ISSUE THREAD

**Issue by Lawrziepan** [quasar098/midi-playground#144]
[wet hands audio.zip](https://github.com/user-attachments/files/16913194/wet.hands.audio.zip)
^ song file

**Comment by Lawrziepan** [comment]
to clarify, the game crashes on opening it

**Comment by DaRealNoteed** [comment]
me too here is crashlog:
*** midi-playground-5.0.0 % python3 main.py
pygame-ce 2.5.2 (SDL 2.30.8, Python 3.12.3)
Traceback (most recent call last):
  File "/Users/***/Desktop/midi-playground-5.0.0/main.py", line 228, in <module>
    main()
  File "/Users/***/Desktop/midi-playground-5.0.0/main.py", line 95, in main
    song_selector = SongSelector()
                    ^^^^^^^^^^^^^^
  File "/Users/***/Desktop/midi-playground-5.0.0/songselector.py", line 129, in __init__
    self.reload_songs()
  File "/Users/***/Desktop/midi-playground-5.0.0/songselector.py", line 146, in reload_songs
    self.songs.append(make_song_from_zip(path))
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/***/Desktop/midi-playground-5.0.0/songselector.py", line 98, in make_song_from_zip
    metadata_info = zf.getinfo("metadata.json")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/zipfile/__init__.py", line 1532, in getinfo
    raise KeyError(
KeyError: "There is no item named 'metadata.json' in the archive"

**Comment by cangerjun** [comment]
zipFlie：wet hands audio.MP3
matadata.json：wet hands audio.mp3
emmm..... Hey bro, it's time for you to pay attention to the file format.

**Comment by cangerjun** [comment]
This is a very classic mistake, and many people have already turned over this mistake, and you are not the first and will not be the last.XD
