### ISSUE TITLE
Config Circular Import

### ISSUE THREAD

**Issue by UserJOhn1241** [quasar098/midi-playground#146]
Error code that opens when I open the midi playground.

pygame-ce 2.5.1 (SDL 2.30.6, Python 3.12.6)
Traceback (most recent call last):
  File "C:\Users\user\Desktop\midi-playground-5.0.0\midi-playground-5.0.0\main.py", line 1, in <module>
    from utils import *
  File "C:\Users\user\Desktop\midi-playground-5.0.0\midi-playground-5.0.0\utils.py", line 5, in <module>
    from config import Config, get_colors
  File "C:\Users\user\Desktop\midi-playground-5.0.0\midi-playground-5.0.0\config.py", line 2, in <module>
    from menu import Menu
  File "C:\Users\user\Desktop\midi-playground-5.0.0\midi-playground-5.0.0\menu.py", line 3, in <module>
    from square import Square
  File "C:\Users\user\Desktop\midi-playground-5.0.0\midi-playground-5.0.0\square.py", line 2, in <module>
    from config import Config
ImportError: cannot import name 'Config' from partially initialized module 'config' (most likely due to a circular import) (C:\Users\user\Desktop\midi-playground-5.0.0\midi-playground-5.0.0\config.py)

C:\Users\user\Desktop\midi-playground-5.0.0\midi-playground-5.0.0>

**Comment by cangerjun** [comment]
When and under what circumstances it appeared?

**Comment by UserJOhn1241** [comment]
> When and under what circumstances it appeared?



> When and under what circumstances it appeared?

When I opened it using the main file. Can you please help me?
