### ISSUE TITLE
error everytime i try to play

### ISSUE THREAD

**Issue by SUPER-MAGIX** [quasar098/midi-playground#15]
so i just downloaded the game, downloaded the requirements, downloaded python (tried 3.9.1 and 3.9.6) but everytime i try to play a song, it loads about 30% and crashes, giving this error:

Traceback (most recent call last):
  File "C:\Users\user\Downloads\midi-playground-1.0.0\midi-playground-1.0.0\main.py", line 135, in <module>
    main()
  File "C:\Users\user\Downloads\midi-playground-1.0.0\midi-playground-1.0.0\main.py", line 105, in main
    if game.start_song(screen):
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Downloads\midi-playground-1.0.0\midi-playground-1.0.0\game.py", line 60, in start_song
    self.safe_areas = self.world.gen_future_bounces(self.notes, update_loading_screen)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Downloads\midi-playground-1.0.0\midi-playground-1.0.0\world.py", line 162, in gen_future_bounces
    assert self.future_bounces is not False, "Recursive bounce generation algorithm failed"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Recursive bounce generation algorithm failed

please help :(  (btw im using cmd)

**Comment by SUPER-MAGIX** [comment]
also even when i try the exe it still gives errors:


Traceback (most recent call last):
  File "main.py", line 135, in <module>
  File "main.py", line 105, in main
  File "game.py", line 60, in start_song
  File "world.py", line 162, in gen_future_bounces
AssertionError: recurs function failed

**Comment by moltenwolfcub** [comment]
This is the same as the issue #14. Might want to help contribute to the conversation there rather than making 2 issues for the same problem

**Comment by SUPER-MAGIX** [comment]
it worked, just edit square size in config.py to 20
