### ISSUE TITLE
Byte must be in range 0..127 - Please help fix it

### ISSUE THREAD

**Issue by Gininabtl** [quasar098/midi-playground#154]
Traceback (most recent call last):
  File "main.py", line 228, in <module>
  File "main.py", line 191, in main
  File "game.py", line 37, in start_song
  File "utils.py", line 119, in read_midi_file
  File "mido\midifiles\midifiles.py", line 321, in __init__
  File "mido\midifiles\midifiles.py", line 359, in _load
  File "mido\midifiles\midifiles.py", line 223, in read_track
  File "mido\midifiles\midifiles.py", line 136, in read_message
OSError: data byte must be in range 0..127

First time i see this please help out

**Comment by quasar098** [comment]
idk
