### ISSUE TITLE
Failed to execute script 'main' due to unhandled exception: (0, 'EnumDisplaySettings', 'No error message available')

### ISSUE THREAD

**Issue by l3salt** [quasar098/midi-playground#20]
Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\Lav Patel\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "utils.py", line 22, in <module>
pywintypes.error: (0, 'EnumDisplaySettings', 'No error message is available')

**Comment by TheCodingCrafter** [comment]
try to use the source code, just run main.py

**Comment by l3salt** [comment]
I tried that and you have to spam click open it. after that is just opens up a blank python command prompt looking tab

**Comment by quasar098** [comment]
it is an issue with pywin32. i am not sure why it is not caught in the try catch. i have to fix this
