### ISSUE TITLE
when i select song and click play, the error appears

### ISSUE THREAD

**Issue by MaybeMEF** [quasar098/midi-playground#23]
when i select song and click play, the error appears

and it says :
Traceback (most recent call last):
  File "main.py", line 135, in <module>
  File "main.py", line 105, in main
  File "game.py", line 60, in start_song
  File "world.py", line 162, in gen_future_bounces
AssertionError: recurs function failed

**Comment by TheCodingCrafter** [comment]
change SQUARE_SIZE in config.py to 20, not 50

**Comment by quasar098** [comment]
> change SQUARE_SIZE in config.py to 20, not 50

although this fix works, i think it is an issue with the square colliding with the peg on bouncegen

i will look into this
