### ISSUE TITLE
'FRAMERATE' Not Defined

### ISSUE THREAD

**Issue by itz-shyam** [quasar098/midi-playground#29]
is it just me? or is there something wrong?

when i run: 
pygame-ce 2.3.0 (SDL 2.26.4, Python 3.10.6)
/home/rootuser/Desktop/shyam/midi/midi-playground-master/main.py:25: Warning: PyGame seems to be running through X11 on top of wayland, instead of wayland directly
  real_screen = pygame.display.set_mode(
Traceback (most recent call last):
  File "/home/rootuser/Desktop/shyam/midi/midi-playground-master/main.py", line 194, in <module>
    main()
  File "/home/rootuser/Desktop/shyam/midi/midi-playground-master/main.py", line 184, in main
    menu.draw(screen, n_frames)
  File "/home/rootuser/Desktop/shyam/midi/midi-playground-master/menu.py", line 76, in draw
    self.anim += 1.8 / FRAMERATE
NameError: name 'FRAMERATE' is not defined

**Comment by quasar098** [comment]
what distro are you on?

**Comment by itz-shyam** [comment]
> wait are you on macos if so then i will not help you

linux us sorta macos ig

**Comment by quasar098** [comment]
> > wait are you on macos if so then i will not help you
> 
> linux us sorta macos ig

completely different

will work on this issue, not sure why framerate is not included, can you try running it from source? 

also, what distro are you on

saying that implies that you are on linux

one distro/flavor of linux is Ubuntu for example, and another is Arch Linux

**Comment by itz-shyam** [comment]
> also, what distro are you on

ubuntu

**Comment by itz-shyam** [comment]
> will work on this issue, not sure why framerate is not included, can you try running it from source?

i did not alter anything but downloaded, unzipped and ran the program..

**Comment by quasar098** [comment]
did you download the binary for windows accidentally or download the source code and then run it?
