### ISSUE TITLE
Upon clicking "Reset to Default", Color Pegs on Bounce becomes a crash button.

### ISSUE THREAD

**Issue by ArchooD2** [quasar098/midi-playground#96]
Unhandled Exception: Failed to execute script 'main' due to "tuple object has no attribute 'split'"
Trace:
`Traceback (most recent call last):
  File "main.py", line 219, in <module>
  File "main.py", line 207, in main
  File "configpage.py", line 381, in draw
  File "pygame_gui\ui_manager.py", line 270, in update
  File "pygame_gui\core\layered_gui_group.py", line 272, in update
  File "pygame\sprite.py", line 556, in update
  File "pygame_gui\elements\ui_drop_down_menu.py", line 803, in update
  File "pygame_gui\elements\ui_drop_down_menu.py", line 124, in start
  File "pygame_gui\elements\ui_button.py", line 135, in __init__
  File "pygame_gui\elements\ui_button.py", line 628, in rebuild_from_changed_theme_data
  File "pygame_gui\elements\ui_button.py", line 700, in rebuild
  File "pygame_gui\core\utility.py", line 600, in translate
  File "i18n\translator.py", line 26, in t
  File "i18n\resource_loader.py", line 97, in search_translation
AttributeError: 'tuple' object has no attribute 'split'`

**Comment by quasar098** [comment]
this is a pygame_gui or pygame issue (i think). i cannot help you here
